
    <tr>

        <td>
            <b>
                {{trans('partners.image')}}
            </b>

        </td>
        <td>
            <b>
                {{trans('partners.name')}}
            </b>
        </td>
        <th>
            <b>
                {{trans('partners.last_name')}}
            </b>

        </th>
        <th>
            <b>
                {{'RFC'}}
            </b>
        </th>
        <th>
            <b>
                {{trans('partners.home_phone')}}
            </b>
        </th>
        <th>
            <b>
                {{trans('partners.email')}}
            </b>
        </th>
        <th>
            <b>
                {{trans('partners.city_name')}}
            </b>
        </th>
        <th>
            <b>
                {{trans('partners.state_name')}}
            </b>
        </th>
        <th>
            <b>
                {{trans('partners.country_name')}}
            </b>
        </th>
    </tr>
